spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/concertreservation?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: application
    password: application

  # Redis
  redis:
    host: localhost
    port: 6379

  # Kafka
  kafka:
    bootstrap-servers: localhost:10000,localhost:10001,localhost:10002
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: alarm-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.roovies.*"
    listener:
      concurrency: 3

# JWT
jwt:
  secret: 542b3dd9b87b2dffa27dc6546c9de4797fa315cbe088fb5f986852890ace3274
  expiration: 600000  # 10ë¶„ (ms)