spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/concertreservation?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: application
    password: application
  jpa:
    hibernate:
      # 매번 실행 시 테이블 생성 후 종료 시 삭제
      ddl-auto: create-drop
    # Hibernate가 사용할 DB 방언 지정 (MySQL용)
    database-platform: org.hibernate.dialect.MySQLDialect
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      host: localhost
      port: 6379

# JWT (테스트 환경)
jwt:
  secret: 542b3dd9b87b2dffa27dc6546c9de4797fa315cbe088fb5f986852890ace3274
  expiration: 600000  # 10분 (ms)

logging:
  level:
    org:
      hibernate:
        # SQL 쿼리 로그를 DEBUG 레벨로 출력
        SQL: DEBUG